{% set name = "pytest-trio" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c01b741819aec2c419555f28944e132d3c711dae1e673d63260809bf92c30c31

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pytest >=3.6
    - trio >=0.15.0
    - async_generator >=1.9
    - outcome

test:
  imports:
    - pytest_trio

about:
  home: https://github.com/python-trio/pytest-trio
  license: MIT
  license_family: MIT
  license_file: LICENSE.MIT
  summary: This is a pytest plugin to help you test projects that use Trio, a friendly library for concurrency and async I/O in Python
  doc_url: https://pytest-trio.readthedocs.io
  dev_url: https://github.com/python-trio/pytest-trio

extra:
  recipe-maintainers:
    - krisevans
    - dhirschfeld
